name: CI

on:
  push:
    branches: [master]
    paths-ignore: ["**.adoc"]
  pull_request:
    paths-ignore: ["**.adoc"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build app
        run: dotnet publish -c Release --os win -f net8.0-windows -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --no-self-contained

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZeldaSaveTool_x64
          path: ZeldaSaveTool/bin/Release/net8.0-windows/win-x64/publish/ZeldaSaveTool.exe
